### PR TITLE
create outdir(s) if they do not already exist

### PR DESCRIPTION
**Pull request by skhilton**
This pull request creates the output directory(ies) if they do not already exist. 

Closes issue #2.

### CODE REVIEW

**Review by jbloom — CHANGES_REQUESTED** [review]
@skhilton:

Can I request the following changes:

- I think there is a bug in line 144 of `main.py`, it should get the directory names of `alignment` *and* `csv`, not `alignment` twice.

- Can you add this update to the `CHANGELOG` and increment the version in `__init__.py` to 0.1.1.

**Review by jbloom — CHANGES_REQUESTED** [review]
@skhilton:

Sorry, I can explain these errors. the second one is simple: the Jupyter notebook test prints out the version of the program. You've changed that to 0.1.1, so that test needs to be updated. Should be as simple as re-running the notebook with the new version. Nothing else changes.

The doctest failure is something that is a lot more subtle. It looks like yesterday they just released `pandas 1.0.0`, and one of the things that does is changes how `NaN` values are handled in integer columns ([see here](https://pandas.pydata.org/pandas-docs/version/1.0.0/user_guide/missing_data.html#missing-data-na)). Hence in the doctest it is now printed as `<NA>` rather than `NaN`. The Travis tests automatically uses the newest `pandas`. One thing we could do is change our code to be compliant with `pandas` 1.0.0. But I don't think we want to do that yet, as many of the other packages we use may not handle `pandas 1.0.0`. So instead for now alter our `setup.py` to require `pandas` still be in the `0.*` series similar to the spec after the comma [here](https://github.com/nextstrain/augur/blob/master/setup.py#L40). That will fix the error, and at some point in the future we can upgrade everything to require `pandas` >= 1.0.0.

**Comment by jbloom** [comment]
@skhilton: Actually, never mind, I thought of a better way to do this. I will push something shortly.

**Comment by skhilton** [comment]
@jbloom: I also haven't worked on protected branches before. Everything looks good to me, how do we merge? Do you have to do it?

**Pull request merged**
